@url =http://localhost:8080/api/user


# Create a user
POST {{url}}
Content-Type: application/json

{
    "email": "mj@neverland.com",
    "passwordHash": "password",
    "admin": false
}

###

# Create an admin user
POST {{url}}
Content-Type: application/json

{
    "email": "tt@kellogg.com",
    "passwordHash": "HiddenPassword",
    "admin": true
}

###

# Login Successfully

POST {{url}}/login
Content-Type: application/json

{
    "email": "mj@neverland.com",
    "passwordHash": "password"
}

###

POST {{url}}/login
Content-Type: application/json

{
    "email": "tt@kellogg.com",
    "passwordHash": "HiddenPassword"
}

###

POST {{url}}/login
Content-Type: application/json

{
    "email": "test@email.com",
    "passwordHash": "password"
}